version: '3.9'

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ['postgres', '-c', 'log_statement=all']
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis
      - redis_config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis_network
volumes:
  postgresql_data:
  redis:
  redis_config:

networks:
  redis_network:
    driver: bridge
